*&---------------------------------------------------------------------*
*&  Include  ZCOMM_MASTER_PBO
*&---------------------------------------------------------------------*

*&SPWIZARD: OUTPUT MODULE FOR TC 'ITAB_TC'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: UPDATE LINES FOR EQUIVALENT SCROLLBAR
MODULE ITAB_TC_CHANGE_TC_ATTR OUTPUT.
*   PERFORM GET_RECORDS .
*  DESCRIBE TABLE IT_RULES LINES ITAB_TC-lines.
ENDMODULE.

*&SPWIZARD: OUTPUT MODULE FOR TC 'ITAB_TC'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GET LINES OF TABLECONTROL
MODULE ITAB_TC_GET_LINES OUTPUT.
  G_ITAB_TC_LINES = SY-LOOPC.
ENDMODULE.
